#if 1 + 1 == 2
#else
#error "1 + 1 != 2"
#endif

#if 1 - 2 == -1
#else
#error "1 - 2 != -1"
#endif

#if 2 * 2 == 4
#else
#error "2 * 2 != 4"
#endif

#if 4 / 2 == 2
#else
#error "4 / 2 != 2"
#endif

#if 4 % 2 == 0
#else
#error "4 % 2 != 0"
#endif

#if 1 << 4 == 16
#else
#error "1 << 4 != 16"
#endif

#if 4 >> 1 == 2
#else
#error "4 >> 1 != 2"
#endif

#if 4 > 1
#else
#error "4 <= 1"
#endif

#if 4 > 4
#error "4 > 4"
#else
#endif

#if 4 >= 1
#else
#error "4 < 1"
#endif

#if 4 >= 4
#else
#error "4 < 4"
#endif

#if 4 < 1
#error "4 < 1"
#endif

#if 4 < 4
#error "4 < 4"
#endif

#if 4 <= 1
#error "4 <= 1"
#endif

#if 4 <= 4
#else
#error "4 > 4"
#endif

#if 1 == 0
#error "1 == 0"
#endif

#if 1 != 1
#error "1 != 1"
#endif

#if 1 ^ 1
#error "1 ^ 1 != 0"
#endif

#if 1 & 1
#else
#error "1 & 1 != 1"
#endif

#if 1 | 1
#else
#error "1 | 1 != 1"
#endif

#if 0 & 1
#error "0 & 1 != 0"
#else
#endif

#if 0 ^ 1
#else
#error "0 ^ 1 != 1"
#endif

#if 0 | 1
#else
#error "0 | 1 != 1"
#endif

#if 1 & 0
#error "1 & 0 != 0"
#else
#endif

#if 1 ^ 0
#else
#error "1 ^ 0 != 1"
#endif

#if 1 | 0
#else
#error "1 | 0 != 1"
#endif

#if 1 || 0
#else
#error "1 || 0 != 1"
#endif

#if 0 || 1
#else
#error "0 || 1 != 1"
#endif

#if 1 || 1
#else
#error "1 || 1 != 1"
#endif

#if 1 && 0
#error "1 && 0 != 0"
#endif

#if 0 && 1
#error "0 && 1 != 0"
#endif

#if 1 && 1
#else
#error "1 && 1 != 1"
#endif

#if !1
#error "!1 != 0"
#endif

#if !0
#else
#error "!0 != 1"
#endif

#if ~0 == -1
#else
#error "~0 != -1"
#endif

#if ~1 == -2
#else
#error "~1 != -2"
#endif

#if +1 != 1
#error "+1 != 1"
#endif

#if true
#else
#error "true == false"
#endif

#if false
#error "false == true"
#endif

#if UNKNOWN_IDENTIFIER_WITH_VERY_LONG_NAME
#error "UNKNOWN_IDENTIFIER_WITH_VERY_LONG_NAME != 0"
#endif

#if 1 ? 0 : 1
#error "1 ? 0 : 1 != 0"
#endif

#if (0)
#error "(0) != 0"
#endif
